export default {
  '88': 'https://images.kiwi.com/airlines/32/47.png',
  'volaris': 'https://images.kiwi.com/airlines/32/Y4.png',
  'nextjet': 'https://images.kiwi.com/airlines/32/2N.png',
  'xl airways france': 'https://images.kiwi.com/airlines/32/SE.png',
  'jc international airlines': 'https://images.kiwi.com/airlines/32/QD.png',
  'alaska seaplanes x4': 'https://images.kiwi.com/airlines/32/X4.png',
  'air serbia': 'https://images.kiwi.com/airlines/32/JU.png',
  'conviasa': 'https://images.kiwi.com/airlines/32/V0.png',
  'aruba airlines': 'https://images.kiwi.com/airlines/32/AG.png',
  'almasria universal airlines': 'https://images.kiwi.com/airlines/32/UJ.png',
  'deutsche bahn': 'https://images.kiwi.com/airlines/32/2A.png',
  'latam peru': 'https://images.kiwi.com/airlines/32/LP.png',
  'arik air': 'https://images.kiwi.com/airlines/32/W3.png',
  'meraj air': 'https://images.kiwi.com/airlines/32/JI.png',
  'norwegian air uk': 'https://images.kiwi.com/airlines/32/DI.png',
  'easyfly': 'https://images.kiwi.com/airlines/32/EF.png',
  'air iceland connect': 'https://images.kiwi.com/airlines/32/NY.png',
  'ethiopian airlines': 'https://images.kiwi.com/airlines/32/ET.png',
  'canadian north': 'https://images.kiwi.com/airlines/32/5T.png',
  'flyadeal': 'https://images.kiwi.com/airlines/32/F3.png',
  'binter canarias': 'https://images.kiwi.com/airlines/32/NT.png',
  'cyprus airways': 'https://images.kiwi.com/airlines/32/CY.png',
  'alsie express': 'https://images.kiwi.com/airlines/32/6I.png',
  'philippine airlines': 'https://images.kiwi.com/airlines/32/PR.png',
  'pal express': 'https://images.kiwi.com/airlines/32/2P.png',
  'dana airlines limited': 'https://images.kiwi.com/airlines/32/9J.png',
  'skywork airlines': 'https://images.kiwi.com/airlines/32/SX.png',
  'mid africa aviation': 'https://images.kiwi.com/airlines/32/8G.png',
  'tassili airlines': 'https://images.kiwi.com/airlines/32/SF.png',
  'jsc uvt aero': 'https://images.kiwi.com/airlines/32/RT.png',
  'nouvelair': 'https://images.kiwi.com/airlines/32/BJ.png',
  'air mediterranean': 'https://images.kiwi.com/airlines/32/MV.png',
  'lufthansa': 'https://images.kiwi.com/airlines/32/LH.png',
  'aerodart': 'https://images.kiwi.com/airlines/32/D4.png',
  'salamair': 'https://images.kiwi.com/airlines/32/OV.png',
  'latam chile': 'https://images.kiwi.com/airlines/32/LA.png',
  'lanmei airlines': 'https://images.kiwi.com/airlines/32/LQ.png',
  'people\'s viennaline pe': 'https://images.kiwi.com/airlines/32/PE.png',
  'starbow airlines': 'https://images.kiwi.com/airlines/32/S9.png',
  'air arabia jordan': 'https://images.kiwi.com/airlines/32/9P.png',
  'saudi arabian airlines': 'https://images.kiwi.com/airlines/32/SV.png',
  'peninsula airways': 'https://images.kiwi.com/airlines/32/KS.png',
  'pelita': 'https://images.kiwi.com/airlines/32/6D.png',
  'ciao air': 'https://images.kiwi.com/airlines/32/99.png',
  'british airways': 'https://images.kiwi.com/airlines/32/BA.png',
  'azerbaijan airlines': 'https://images.kiwi.com/airlines/32/J2.png',
  'amaszonas uruguay': 'https://images.kiwi.com/airlines/32/Z7.png',
  'amaszonas del paraguay s.a. lineas aereas': 'https://images.kiwi.com/airlines/32/ZP.png',
  'air tahiti': 'https://images.kiwi.com/airlines/32/VT.png',
  'emirates': 'https://images.kiwi.com/airlines/32/EK.png',
  'nokscoot': 'https://images.kiwi.com/airlines/32/XW.png',
  'thai smile': 'https://images.kiwi.com/airlines/32/WE.png',
  'atifly': 'https://images.kiwi.com/airlines/32/A1.png',
  'med-view airline': 'https://images.kiwi.com/airlines/32/VL.png',
  'air moldova': 'https://images.kiwi.com/airlines/32/9U.png',
  'air seychelles': 'https://images.kiwi.com/airlines/32/HM.png',
  'leeward islands air transport': 'https://images.kiwi.com/airlines/32/LI.png',
  'tandem aero': 'https://images.kiwi.com/airlines/32/TQ.png',
  'thai sky airlines': 'https://images.kiwi.com/airlines/32/9I.png',
  'sunexpress': 'https://images.kiwi.com/airlines/32/XG.png',
  'lugansk airlines': 'https://images.kiwi.com/airlines/32/L7.png',
  'tunisair express': 'https://images.kiwi.com/airlines/32/UG.png',
  'taca peru': 'https://images.kiwi.com/airlines/32/T0.png',
  'alaska seaplane service': 'https://images.kiwi.com/airlines/32/J5.png',
  'eagle atlantic airlines': 'https://images.kiwi.com/airlines/32/E2.png',
  'nile air': 'https://images.kiwi.com/airlines/32/NP.png',
  'corendon dutch airlines b.v.': 'https://images.kiwi.com/airlines/32/CD.png',
  'widerøe': 'https://images.kiwi.com/airlines/32/WF.png',
  'air comet chile': 'https://images.kiwi.com/airlines/32/3I.png',
  'hankook airline': 'https://images.kiwi.com/airlines/32/HN.png',
  'lsm international ': 'https://images.kiwi.com/airlines/32/II.png',
  'austral brasil': 'https://images.kiwi.com/airlines/32/W7.png',
  'airtran airways': 'https://images.kiwi.com/airlines/32/FL.png',
  'skywest': 'https://images.kiwi.com/airlines/32/OO.png',
  'air manas': 'https://images.kiwi.com/airlines/32/ZM.png',
  'anadolujet': 'https://images.kiwi.com/airlines/32/00.png',
  'serbian airlines': 'https://images.kiwi.com/airlines/32/S1.png',
  'silkair': 'https://images.kiwi.com/airlines/32/MI.png',
  'zanair': 'https://images.kiwi.com/airlines/32/B4.png',
  'niki': 'https://images.kiwi.com/airlines/32/HG.png',
  'mhs aviation gmbh': 'https://images.kiwi.com/airlines/32/M2.png',
  'maryland air': 'https://images.kiwi.com/airlines/32/M1.png',
  'air lituanica': 'https://images.kiwi.com/airlines/32/LT.png',
  'flylal': 'https://images.kiwi.com/airlines/32/TE.png',
  'tuifly (x3)': 'https://images.kiwi.com/airlines/32/11.png',
  'jeju air': 'https://images.kiwi.com/airlines/32/7C.png',
  'finnair': 'https://images.kiwi.com/airlines/32/AY.png',
  'avianca': 'https://images.kiwi.com/airlines/32/AV.png',
  'nordstar airlines': 'https://images.kiwi.com/airlines/32/Y7.png',
  'canary fly': 'https://images.kiwi.com/airlines/32/PM.png',
  'royal jordanian': 'https://images.kiwi.com/airlines/32/RJ.png',
  'atlasglobal': 'https://images.kiwi.com/airlines/32/KK.png',
  'first air': 'https://images.kiwi.com/airlines/32/7F.png',
  'air plus comet': 'https://images.kiwi.com/airlines/32/A7.png',
  'shenzhen airlines': 'https://images.kiwi.com/airlines/32/ZH.png',
  'qatar airways': 'https://images.kiwi.com/airlines/32/QR.png',
  'air guyane': 'https://images.kiwi.com/airlines/32/GG.png',
  'air guinee express': 'https://images.kiwi.com/airlines/32/2U.png',
  'nam air': 'https://images.kiwi.com/airlines/32/IN.png',
  'latam colombia': 'https://images.kiwi.com/airlines/32/4C.png',
  'africa west': 'https://images.kiwi.com/airlines/32/FK.png',
  'fly dubai': 'https://images.kiwi.com/airlines/32/FZ.png',
  'air sinai': 'https://images.kiwi.com/airlines/32/4D.png',
  'alitalia express': 'https://images.kiwi.com/airlines/32/XM.png',
  'air nostrum': 'https://images.kiwi.com/airlines/32/YW.png',
  'saudigulf airlines': 'https://images.kiwi.com/airlines/32/6S.png',
  'luxair': 'https://images.kiwi.com/airlines/32/LG.png',
  'neptune air sdn bhd': 'https://images.kiwi.com/airlines/32/N7.png',
  'titan airways': 'https://images.kiwi.com/airlines/32/ZT.png',
  'tampa': 'https://images.kiwi.com/airlines/32/QT.png',
  'airlink (saa)': 'https://images.kiwi.com/airlines/32/4Z.png',
  'air libert': 'https://images.kiwi.com/airlines/32/VD.png',
  'air wisconsin': 'https://images.kiwi.com/airlines/32/ZW.png',
  'america west airlines': 'https://images.kiwi.com/airlines/32/HP.png',
  'air kiribati': 'https://images.kiwi.com/airlines/32/4A.png',
  'singapore airlines': 'https://images.kiwi.com/airlines/32/SQ.png',
  'somon air': 'https://images.kiwi.com/airlines/32/SZ.png',
  'vim airlines': 'https://images.kiwi.com/airlines/32/NN.png',
  'airpanama': 'https://images.kiwi.com/airlines/32/7P.png',
  'aerolitoral': 'https://images.kiwi.com/airlines/32/5D.png',
  'aircalin': 'https://images.kiwi.com/airlines/32/SB.png',
  'air salone': 'https://images.kiwi.com/airlines/32/20.png',
  'alliance airlines': 'https://images.kiwi.com/airlines/32/QQ.png',
  'air italy': 'https://images.kiwi.com/airlines/32/I9.png',
  'oman air': 'https://images.kiwi.com/airlines/32/WY.png',
  'ural airlines': 'https://images.kiwi.com/airlines/32/U6.png',
  'eurolot': 'https://images.kiwi.com/airlines/32/K2.png',
  'belair': 'https://images.kiwi.com/airlines/32/4T.png',
  'albastar': 'https://images.kiwi.com/airlines/32/AP.png',
  'air kyrgyzstan': 'https://images.kiwi.com/airlines/32/QH.png',
  'komiaviatrans': 'https://images.kiwi.com/airlines/32/KO.png',
  'white airways': 'https://images.kiwi.com/airlines/32/WI.png',
  'aer lingus': 'https://images.kiwi.com/airlines/32/EI.png',
  'qantas': 'https://images.kiwi.com/airlines/32/QF.png',
  'british mediterranean airways': 'https://images.kiwi.com/airlines/32/KJ.png',
  'izhavia': 'https://images.kiwi.com/airlines/32/I8.png',
  'jetstar japan': 'https://images.kiwi.com/airlines/32/GK.png',
  'air greenland': 'https://images.kiwi.com/airlines/32/GL.png',
  'star peru': 'https://images.kiwi.com/airlines/32/2I.png',
  'hop!': 'https://images.kiwi.com/airlines/32/A5.png',
  'air niugini': 'https://images.kiwi.com/airlines/32/PX.png',
  'auric air': 'https://images.kiwi.com/airlines/32/UI.png',
  'hahn air': 'https://images.kiwi.com/airlines/32/H1.png',
  'air arabia egypt': 'https://images.kiwi.com/airlines/32/E5.png',
  'hawaiian airlines': 'https://images.kiwi.com/airlines/32/HA.png',
  'qazaq air': 'https://images.kiwi.com/airlines/32/IQ.png',
  'red wings': 'https://images.kiwi.com/airlines/32/WZ.png',
  'horizon airlines': 'https://images.kiwi.com/airlines/32/BN.png',
  'cargojet airways': 'https://images.kiwi.com/airlines/32/W8.png',
  'red jet andes': 'https://images.kiwi.com/airlines/32/PT.png',
  'indigo airlines': 'https://images.kiwi.com/airlines/32/6E.png',
  'air indus': 'https://images.kiwi.com/airlines/32/I6.png',
  'air tanzania': 'https://images.kiwi.com/airlines/32/TC.png',
  'air saint pierre': 'https://images.kiwi.com/airlines/32/PJ.png',
  'zoom airlines': 'https://images.kiwi.com/airlines/32/Z4.png',
  'intercaribbean airways': 'https://images.kiwi.com/airlines/32/JY.png',
  'air jamaica': 'https://images.kiwi.com/airlines/32/JM.png',
  'sky express': 'https://images.kiwi.com/airlines/32/GQ.png',
  'nesma air': 'https://images.kiwi.com/airlines/32/NA.png',
  'michael airlines': 'https://images.kiwi.com/airlines/32/DF.png',
  'aviabus': 'https://images.kiwi.com/airlines/32/U1.png',
  'copenhagen express': 'https://images.kiwi.com/airlines/32/0X.png',
  'alitalia cityliner': 'https://images.kiwi.com/airlines/32/CT.png',
  'air canada': 'https://images.kiwi.com/airlines/32/AC.png',
  'onur air': 'https://images.kiwi.com/airlines/32/8Q.png',
  'lacsa': 'https://images.kiwi.com/airlines/32/LR.png',
  'air bangladesh': 'https://images.kiwi.com/airlines/32/B9.png',
  'aeroline gmbh': 'https://images.kiwi.com/airlines/32/7E.png',
  'air wales': 'https://images.kiwi.com/airlines/32/6G.png',
  'lan express': 'https://images.kiwi.com/airlines/32/LU.png',
  'atlas air': 'https://images.kiwi.com/airlines/32/5Y.png',
  'aserca airlines': 'https://images.kiwi.com/airlines/32/R7.png',
  'alaska airlines': 'https://images.kiwi.com/airlines/32/AS.png',
  'air ivoire': 'https://images.kiwi.com/airlines/32/VU.png',
  'cityjet': 'https://images.kiwi.com/airlines/32/WX.png',
  'tigerair taiwan': 'https://images.kiwi.com/airlines/32/IT.png',
  'ana wings': 'https://images.kiwi.com/airlines/32/EH.png',
  'blue air': 'https://images.kiwi.com/airlines/32/0B.png',
  'regional express': 'https://images.kiwi.com/airlines/32/ZL.png',
  'air choice one': 'https://images.kiwi.com/airlines/32/3E.png',
  'fastjet': 'https://images.kiwi.com/airlines/32/FN.png',
  'air chathams': 'https://images.kiwi.com/airlines/32/CV.png',
  'china eastern airlines': 'https://images.kiwi.com/airlines/32/MU.png',
  'sun country airlines': 'https://images.kiwi.com/airlines/32/SY.png',
  'air madagascar': 'https://images.kiwi.com/airlines/32/MD.png',
  'tus airways': 'https://images.kiwi.com/airlines/32/U8.png',
  'rossiya-russian airlines': 'https://images.kiwi.com/airlines/32/FV.png',
  'aeroflot-don': 'https://images.kiwi.com/airlines/32/D9.png',
  'air madrid': 'https://images.kiwi.com/airlines/32/NM.png',
  'air finland': 'https://images.kiwi.com/airlines/32/OF.png',
  'air bagan': 'https://images.kiwi.com/airlines/32/W9.png',
  'air koryo': 'https://images.kiwi.com/airlines/32/JS.png',
  'proflight zambia': 'https://images.kiwi.com/airlines/32/P0.png',
  'air luxor': 'https://images.kiwi.com/airlines/32/LK.png',
  'air mauritius': 'https://images.kiwi.com/airlines/32/MK.png',
  'aer arann': 'https://images.kiwi.com/airlines/32/RE.png',
  'porter airlines': 'https://images.kiwi.com/airlines/32/PD.png',
  'fiji airways': 'https://images.kiwi.com/airlines/32/FJ.png',
  'cambodia bayon airlines': 'https://images.kiwi.com/airlines/32/BD.png',
  'astair': 'https://images.kiwi.com/airlines/32/8D.png',
  'aeropelican air services': 'https://images.kiwi.com/airlines/32/OT.png',
  'asian spirit': 'https://images.kiwi.com/airlines/32/6K.png',
  'iraero': 'https://images.kiwi.com/airlines/32/IO.png',
  'air austral': 'https://images.kiwi.com/airlines/32/UU.png',
  'ukraine international airlines': 'https://images.kiwi.com/airlines/32/PS.png',
  'egyptair': 'https://images.kiwi.com/airlines/32/MS.png',
  'aerosur': 'https://images.kiwi.com/airlines/32/5L.png',
  'berjaya air': 'https://images.kiwi.com/airlines/32/J8.png',
  'avient aviation': 'https://images.kiwi.com/airlines/32/Z3.png',
  'avialeasing aviation company': 'https://images.kiwi.com/airlines/32/EC.png',
  'aerolineas galapagos (aerogal)': 'https://images.kiwi.com/airlines/32/2K.png',
  'air caraïbes': 'https://images.kiwi.com/airlines/32/TX.png',
  'atlantic airways': 'https://images.kiwi.com/airlines/32/RC.png',
  'star flyer': 'https://images.kiwi.com/airlines/32/7G.png',
  'renfe': 'https://images.kiwi.com/airlines/32/4R.png',
  'mega maledives airline': 'https://images.kiwi.com/airlines/32/LV.png',
  'small planet airline': 'https://images.kiwi.com/airlines/32/P7.png',
  'british international helicopters': 'https://images.kiwi.com/airlines/32/BS.png',
  'blue1': 'https://images.kiwi.com/airlines/32/KF.png',
  'latam brasil': 'https://images.kiwi.com/airlines/32/JJ.png',
  'bemidji airlines': 'https://images.kiwi.com/airlines/32/CH.png',
  'bering air': 'https://images.kiwi.com/airlines/32/8E.png',
  'belavia belarusian airlines': 'https://images.kiwi.com/airlines/32/B2.png',
  'bulgaria air': 'https://images.kiwi.com/airlines/32/FB.png',
  'tianjin airlines': 'https://images.kiwi.com/airlines/32/GS.png',
  'french blue': 'https://images.kiwi.com/airlines/32/BF.png',
  'air astana': 'https://images.kiwi.com/airlines/32/KC.png',
  'orchid airlines': 'https://images.kiwi.com/airlines/32/OI.png',
  'aero contractors': 'https://images.kiwi.com/airlines/32/AJ.png',
  'air dolomiti': 'https://images.kiwi.com/airlines/32/EN.png',
  'avia traffic airline': 'https://images.kiwi.com/airlines/32/YK.png',
  'air caledonie': 'https://images.kiwi.com/airlines/32/TY.png',
  'virgin america': 'https://images.kiwi.com/airlines/32/VX.png',
  'air vanuatu': 'https://images.kiwi.com/airlines/32/NF.png',
  'skywise': 'https://images.kiwi.com/airlines/32/S8.png',
  'regional air services': 'https://images.kiwi.com/airlines/32/8N.png',
  'china united airlines': 'https://images.kiwi.com/airlines/32/HR.png',
  'cimber air': 'https://images.kiwi.com/airlines/32/QI.png',
  'coastal air': 'https://images.kiwi.com/airlines/32/DQ.png',
  'comores airlines': 'https://images.kiwi.com/airlines/32/KR.png',
  'consorcio aviaxsa': 'https://images.kiwi.com/airlines/32/6A.png',
  'croatia airlines': 'https://images.kiwi.com/airlines/32/OU.png',
  'grupo taca': 'https://images.kiwi.com/airlines/32/TA.png',
  'helvetic airways': 'https://images.kiwi.com/airlines/32/2L.png',
  'trujet': 'https://images.kiwi.com/airlines/32/2T.png',
  'gulf air bahrain': 'https://images.kiwi.com/airlines/32/GF.png',
  'air corsica': 'https://images.kiwi.com/airlines/32/XK.png',
  'druk air': 'https://images.kiwi.com/airlines/32/KB.png',
  'hainan airlines': 'https://images.kiwi.com/airlines/32/HU.png',
  'corsairfly': 'https://images.kiwi.com/airlines/32/SS.png',
  'china southern airlines': 'https://images.kiwi.com/airlines/32/CZ.png',
  'great lakes airlines': 'https://images.kiwi.com/airlines/32/ZK.png',
  'dominicana de aviaci': 'https://images.kiwi.com/airlines/32/DO.png',
  'domodedovo airlines': 'https://images.kiwi.com/airlines/32/E3.png',
  'eagle air': 'https://images.kiwi.com/airlines/32/H7.png',
  'east african': 'https://images.kiwi.com/airlines/32/QU.png',
  'eastern airways': 'https://images.kiwi.com/airlines/32/T3.png',
  'el-buraq air transport': 'https://images.kiwi.com/airlines/32/UZ.png',
  'empresa ecuatoriana de aviacion': 'https://images.kiwi.com/airlines/32/EU.png',
  'eritrean airlines': 'https://images.kiwi.com/airlines/32/B8.png',
  'european air express': 'https://images.kiwi.com/airlines/32/EA.png',
  'excel airways': 'https://images.kiwi.com/airlines/32/JN.png',
  'express one international': 'https://images.kiwi.com/airlines/32/EO.png',
  'freedom air': 'https://images.kiwi.com/airlines/32/FP.png',
  'cubana de aviación': 'https://images.kiwi.com/airlines/32/CU.png',
  'cathay pacific': 'https://images.kiwi.com/airlines/32/CX.png',
  'eastar jet': 'https://images.kiwi.com/airlines/32/ZE.png',
  'surinam airways': 'https://images.kiwi.com/airlines/32/PY.png',
  'olympic air': 'https://images.kiwi.com/airlines/32/OA.png',
  'apg airlines': 'https://images.kiwi.com/airlines/32/GP.png',
  'paramount airways': 'https://images.kiwi.com/airlines/32/I7.png',
  'gazpromavia': 'https://images.kiwi.com/airlines/32/4G.png',
  'georgian airways': 'https://images.kiwi.com/airlines/32/A9.png',
  'georgian national airlines': 'https://images.kiwi.com/airlines/32/QB.png',
  'ghana international airlines': 'https://images.kiwi.com/airlines/32/G0.png',
  'gojet airlines': 'https://images.kiwi.com/airlines/32/G7.png',
  'air transat': 'https://images.kiwi.com/airlines/32/TS.png',
  'hex air': 'https://images.kiwi.com/airlines/32/UD.png',
  'ibex airlines': 'https://images.kiwi.com/airlines/32/FW.png',
  'etihad airways': 'https://images.kiwi.com/airlines/32/EY.png',
  'sansa air': 'https://images.kiwi.com/airlines/32/RZ.png',
  'severstal air company': 'https://images.kiwi.com/airlines/32/D2.png',
  'lot polish airlines': 'https://images.kiwi.com/airlines/32/LO.png',
  'indian airlines': 'https://images.kiwi.com/airlines/32/IC.png',
  'interair south africa': 'https://images.kiwi.com/airlines/32/D6.png',
  'iran air': 'https://images.kiwi.com/airlines/32/IR.png',
  'iran aseman airlines': 'https://images.kiwi.com/airlines/32/EP.png',
  'latin american wings': 'https://images.kiwi.com/airlines/32/LW.png',
  'batik air': 'https://images.kiwi.com/airlines/32/ID.png',
  'islena de inversiones': 'https://images.kiwi.com/airlines/32/WC.png',
  'itek air': 'https://images.kiwi.com/airlines/32/GI.png',
  'jal express': 'https://images.kiwi.com/airlines/32/JC.png',
  'jalways': 'https://images.kiwi.com/airlines/32/JO.png',
  'israir': 'https://images.kiwi.com/airlines/32/6H.png',
  'maya island air': 'https://images.kiwi.com/airlines/32/2M.png',
  'kam air': 'https://images.kiwi.com/airlines/32/RQ.png',
  'kavminvodyavia': 'https://images.kiwi.com/airlines/32/KV.png',
  'kenmore air': 'https://images.kiwi.com/airlines/32/M5.png',
  'kish air': 'https://images.kiwi.com/airlines/32/Y9.png',
  'kogalymavia air company': 'https://images.kiwi.com/airlines/32/7K.png',
  'kuban airlines': 'https://images.kiwi.com/airlines/32/GW.png',
  'ernest airlines': 'https://images.kiwi.com/airlines/32/EG.png',
  'lauda air': 'https://images.kiwi.com/airlines/32/NG.png',
  'libyan arab airlines': 'https://images.kiwi.com/airlines/32/LN.png',
  'royal air maroc': 'https://images.kiwi.com/airlines/32/AT.png',
  'martinair': 'https://images.kiwi.com/airlines/32/MP.png',
  'merpati nusantara airlines': 'https://images.kiwi.com/airlines/32/MZ.png',
  'mesa airlines': 'https://images.kiwi.com/airlines/32/YV.png',
  'mexicana de aviaci': 'https://images.kiwi.com/airlines/32/MX.png',
  'midwest airlines': 'https://images.kiwi.com/airlines/32/YX.png',
  'midwest airlines (egypt)': 'https://images.kiwi.com/airlines/32/MY.png',
  'myway airlines': 'https://images.kiwi.com/airlines/32/8I.png',
  'montenegro airlines': 'https://images.kiwi.com/airlines/32/YM.png',
  'moskovia airlines': 'https://images.kiwi.com/airlines/32/3R.png',
  'motor sich': 'https://images.kiwi.com/airlines/32/M9.png',
  'pacific coastal airline': 'https://images.kiwi.com/airlines/32/8P.png',
  'national jet systems': 'https://images.kiwi.com/airlines/32/NC.png',
  'nauru air corporation': 'https://images.kiwi.com/airlines/32/ON.png',
  'thomas cook airlines': 'https://images.kiwi.com/airlines/32/FQ.png',
  'volotea': 'https://images.kiwi.com/airlines/32/V7.png',
  'yangon airways': 'https://images.kiwi.com/airlines/32/HK.png',
  'nepal airlines': 'https://images.kiwi.com/airlines/32/RA.png',
  'new england airlines': 'https://images.kiwi.com/airlines/32/EJ.png',
  'northern dene airways': 'https://images.kiwi.com/airlines/32/U7.png',
  'northwestern air': 'https://images.kiwi.com/airlines/32/J3.png',
  'accesrail': 'https://images.kiwi.com/airlines/32/9B.png',
  'japan transocean air': 'https://images.kiwi.com/airlines/32/NU.png',
  'korean air': 'https://images.kiwi.com/airlines/32/KE.png',
  'oceanic airlines': 'https://images.kiwi.com/airlines/32/O2.png',
  'omni air international': 'https://images.kiwi.com/airlines/32/OY.png',
  'ostfriesische lufttransport': 'https://images.kiwi.com/airlines/32/OL.png',
  'tacv': 'https://images.kiwi.com/airlines/32/VR.png',
  'pan air': 'https://images.kiwi.com/airlines/32/PV.png',
  'polar airlines': 'https://images.kiwi.com/airlines/32/PO.png',
  'avianca brazil': 'https://images.kiwi.com/airlines/32/O6.png',
  'plus ultra lineas aereas': 'https://images.kiwi.com/airlines/32/PU.png',
  'lao airlines': 'https://images.kiwi.com/airlines/32/QV.png',
  'buddha air': 'https://images.kiwi.com/airlines/32/U4.png',
  'eco jet': 'https://images.kiwi.com/airlines/32/8J.png',
  'pinnacle airlines': 'https://images.kiwi.com/airlines/32/9E.png',
  'polynesian airlines': 'https://images.kiwi.com/airlines/32/PH.png',
  'potomac air': 'https://images.kiwi.com/airlines/32/BK.png',
  'pegas fly': 'https://images.kiwi.com/airlines/32/IK.png',
  'orenburzhye airline': 'https://images.kiwi.com/airlines/32/O7.png',
  'fly blue crane': 'https://images.kiwi.com/airlines/32/7B.png',
  'airlines png': 'https://images.kiwi.com/airlines/32/CG.png',
  'loganair lm': 'https://images.kiwi.com/airlines/32/LM.png',
  'republic express airlines': 'https://images.kiwi.com/airlines/32/RH.png',
  'air rarotonga': 'https://images.kiwi.com/airlines/32/GZ.png',
  'orbest': 'https://images.kiwi.com/airlines/32/6O.png',
  'sata international': 'https://images.kiwi.com/airlines/32/S4.png',
  'american eagle airlines': 'https://images.kiwi.com/airlines/32/MQ.png',
  'sibaviatrans': 'https://images.kiwi.com/airlines/32/5M.png',
  'sama airlines': 'https://images.kiwi.com/airlines/32/ZS.png',
  'siem reap airways': 'https://images.kiwi.com/airlines/32/FT.png',
  'skyservice airlines': 'https://images.kiwi.com/airlines/32/5G.png',
  'servicios de transportes a': 'https://images.kiwi.com/airlines/32/FS.png',
  'sudan airways': 'https://images.kiwi.com/airlines/32/SD.png',
  'sriwijaya air': 'https://images.kiwi.com/airlines/32/SJ.png',
  'syrian arab airlines': 'https://images.kiwi.com/airlines/32/RB.png',
  'shandong airlines': 'https://images.kiwi.com/airlines/32/SC.png',
  'shuttle america': 'https://images.kiwi.com/airlines/32/S5.png',
  'baikotovitchestrian airlines ': 'https://images.kiwi.com/airlines/32/BU.png',
  'tiara air': 'https://images.kiwi.com/airlines/32/3P.png',
  'borajet': 'https://images.kiwi.com/airlines/32/YB.png',
  'trans air congo': 'https://images.kiwi.com/airlines/32/Q8.png',
  'transasia airways': 'https://images.kiwi.com/airlines/32/GE.png',
  'royal falcon': 'https://images.kiwi.com/airlines/32/RL.png',
  'turkmenistan airlines': 'https://images.kiwi.com/airlines/32/T5.png',
  'neos air': 'https://images.kiwi.com/airlines/32/NO.png',
  'fly one': 'https://images.kiwi.com/airlines/32/5F.png',
  'taag angola airlines': 'https://images.kiwi.com/airlines/32/DT.png',
  'trans states airlines': 'https://images.kiwi.com/airlines/32/AX.png',
  'beijing capital airlines': 'https://images.kiwi.com/airlines/32/JD.png',
  'azimuth': 'https://images.kiwi.com/airlines/32/A4.png',
  'turan air': 'https://images.kiwi.com/airlines/32/3T.png',
  'usa3000 airlines': 'https://images.kiwi.com/airlines/32/U5.png',
  'um airlines': 'https://images.kiwi.com/airlines/32/UF.png',
  'us airways': 'https://images.kiwi.com/airlines/32/US.png',
  'welcome air': 'https://images.kiwi.com/airlines/32/2W.png',
  'west coast air': 'https://images.kiwi.com/airlines/32/8O.png',
  'wind jet': 'https://images.kiwi.com/airlines/32/IV.png',
  'xiamen airlines': 'https://images.kiwi.com/airlines/32/MF.png',
  'yemenia': 'https://images.kiwi.com/airlines/32/IY.png',
  'air kazakhstan': 'https://images.kiwi.com/airlines/32/9Y.png',
  'aurora airlines': 'https://images.kiwi.com/airlines/32/HZ.png',
  'virgin atlantic airways': 'https://images.kiwi.com/airlines/32/VS.png',
  's7 airlines': 'https://images.kiwi.com/airlines/32/S7.png',
  'carnival air lines': 'https://images.kiwi.com/airlines/32/KW.png',
  'uni air': 'https://images.kiwi.com/airlines/32/B7.png',
  'gomelavia': 'https://images.kiwi.com/airlines/32/YD.png',
  'air mozambique': 'https://images.kiwi.com/airlines/32/TM.png',
  'germania flug': 'https://images.kiwi.com/airlines/32/GM.png',
  'virgin pacific': 'https://images.kiwi.com/airlines/32/VH.png',
  'canadian national airways': 'https://images.kiwi.com/airlines/32/CN.png',
  'line blue': 'https://images.kiwi.com/airlines/32/L8.png',
  'dennis sky': 'https://images.kiwi.com/airlines/32/DH.png',
  'zz': 'https://images.kiwi.com/airlines/32/ZZ.png',
  'latam paraguay': 'https://images.kiwi.com/airlines/32/PZ.png',
  'tame': 'https://images.kiwi.com/airlines/32/EQ.png',
  'alak': 'https://images.kiwi.com/airlines/32/J4.png',
  'salmon air': 'https://images.kiwi.com/airlines/32/S6.png',
  'amsterdam airlines': 'https://images.kiwi.com/airlines/32/WD.png',
  'stp airways': 'https://images.kiwi.com/airlines/32/8F.png',
  'med airways': 'https://images.kiwi.com/airlines/32/7Y.png',
  'skyjet airlines': 'https://images.kiwi.com/airlines/32/UQ.png',
  'air volga': 'https://images.kiwi.com/airlines/32/G6.png',
  'euroline': 'https://images.kiwi.com/airlines/32/4L.png',
  'athens airways': 'https://images.kiwi.com/airlines/32/ZF.png',
  'starline.kz': 'https://images.kiwi.com/airlines/32/DZ.png',
  'gryphon airlines': 'https://images.kiwi.com/airlines/32/6P.png',
  'joy air': 'https://images.kiwi.com/airlines/32/JR.png',
  'mdlr airlines': 'https://images.kiwi.com/airlines/32/9H.png',
  'tailwind airlines': 'https://images.kiwi.com/airlines/32/TI.png',
  'maldivian': 'https://images.kiwi.com/airlines/32/Q2.png',
  'fuji dream airlines': 'https://images.kiwi.com/airlines/32/JH.png',
  'belleair': 'https://images.kiwi.com/airlines/32/LZ.png',
  'congo express': 'https://images.kiwi.com/airlines/32/XZ.png',
  'uzbekistan airways': 'https://images.kiwi.com/airlines/32/HY.png',
  'tibet airlines': 'https://images.kiwi.com/airlines/32/TV.png',
  'utair-express': 'https://images.kiwi.com/airlines/32/UR.png',
  'allegiant air': 'https://images.kiwi.com/airlines/32/G4.png',
  'seaborne airlines': 'https://images.kiwi.com/airlines/32/BB.png',
  'kulula': 'https://images.kiwi.com/airlines/32/MN.png',
  'i-fly': 'https://images.kiwi.com/airlines/32/I4.png',
  'airrussia': 'https://images.kiwi.com/airlines/32/R8.png',
  'domenican airlines': 'https://images.kiwi.com/airlines/32/D1.png',
  'lionxpress': 'https://images.kiwi.com/airlines/32/C4.png',
  'royal european airlines': 'https://images.kiwi.com/airlines/32/69.png',
  'lte international airways': 'https://images.kiwi.com/airlines/32/XO.png',
  'huaxia': 'https://images.kiwi.com/airlines/32/G5.png',
  'jobair': 'https://images.kiwi.com/airlines/32/3B.png',
  'air mekong': 'https://images.kiwi.com/airlines/32/P8.png',
  'air hamburg (aho)': 'https://images.kiwi.com/airlines/32/HH.png',
  'caucasus airlines': 'https://images.kiwi.com/airlines/32/NS.png',
  'flyvlm': 'https://images.kiwi.com/airlines/32/VO.png',
  'vickjet': 'https://images.kiwi.com/airlines/32/KT.png',
  'bvi airways': 'https://images.kiwi.com/airlines/32/XV.png',
  'zambezi airlines (zma)': 'https://images.kiwi.com/airlines/32/ZJ.png',
  'polet airlines (priv)': 'https://images.kiwi.com/airlines/32/YQ.png',
  '12 north': 'https://images.kiwi.com/airlines/32/12.png',
  'mauritania airlines international': 'https://images.kiwi.com/airlines/32/L6.png',
  'colorful guizhou airlines': 'https://images.kiwi.com/airlines/32/GY.png',
  'chalair': 'https://images.kiwi.com/airlines/32/CE.png',
  'sun d\'or': 'https://images.kiwi.com/airlines/32/7L.png',
  'avies': 'https://images.kiwi.com/airlines/32/U3.png',
  'access air': 'https://images.kiwi.com/airlines/32/ZA.png',
  'atlantis european airways': 'https://images.kiwi.com/airlines/32/TD.png',
  'via air': 'https://images.kiwi.com/airlines/32/VC.png',
  'dat danish air transport': 'https://images.kiwi.com/airlines/32/DX.png',
  'daallo airlines': 'https://images.kiwi.com/airlines/32/D3.png',
  'iraqi airways': 'https://images.kiwi.com/airlines/32/IA.png',
  '1time airline': 'https://images.kiwi.com/airlines/32/1T.png',
  'shanghai airlines': 'https://images.kiwi.com/airlines/32/FM.png',
  'atlasglobal ukraine': 'https://images.kiwi.com/airlines/32/UH.png',
  'spanair': 'https://images.kiwi.com/airlines/32/JK.png',
  'santa barbara airlines': 'https://images.kiwi.com/airlines/32/S3.png',
  'skyways express': 'https://images.kiwi.com/airlines/32/JZ.png',
  'seaport airlines': 'https://images.kiwi.com/airlines/32/K5.png',
  'sterling airlines': 'https://images.kiwi.com/airlines/32/NB.png',
  'volga-dnepr airlines': 'https://images.kiwi.com/airlines/32/VI.png',
  'virgin nigeria airways': 'https://images.kiwi.com/airlines/32/VK.png',
  'vlm airlines': 'https://images.kiwi.com/airlines/32/VG.png',
  'air cargo carriers': 'https://images.kiwi.com/airlines/32/2Q.png',
  'czech airlines': 'https://images.kiwi.com/airlines/32/OK.png',
  'small planet airlines': 'https://images.kiwi.com/airlines/32/5P.png',
  'solomon airlines': 'https://images.kiwi.com/airlines/32/IE.png',
  'solaseed air': 'https://images.kiwi.com/airlines/32/6J.png',
  'safi airlines': 'https://images.kiwi.com/airlines/32/4Q.png',
  'pan am world airways dominicana': 'https://images.kiwi.com/airlines/32/7Q.png',
  'vip ecuador': 'https://images.kiwi.com/airlines/32/V6.png',
  'catovair': 'https://images.kiwi.com/airlines/32/OC.png',
  'halcyonair': 'https://images.kiwi.com/airlines/32/7Z.png',
  'business aviation': 'https://images.kiwi.com/airlines/32/4P.png',
  'air zimbabwe': 'https://images.kiwi.com/airlines/32/UM.png',
  'smartlynx airlines': 'https://images.kiwi.com/airlines/32/6Y.png',
  'air algerie': 'https://images.kiwi.com/airlines/32/AH.png',
  'elysian airlines': 'https://images.kiwi.com/airlines/32/E4.png',
  'trenitalia': 'https://images.kiwi.com/airlines/32/7T.png',
  'mistral air': 'https://images.kiwi.com/airlines/32/M4.png',
  'icelandair': 'https://images.kiwi.com/airlines/32/FI.png',
  'zenith international airline': 'https://images.kiwi.com/airlines/32/ZN.png',
  'hellenic imperial airways': 'https://images.kiwi.com/airlines/32/HT.png',
  'arik niger': 'https://images.kiwi.com/airlines/32/Q9.png',
  'transholding system': 'https://images.kiwi.com/airlines/32/YO.png',
  'fly colombia ( interliging flights )': 'https://images.kiwi.com/airlines/32/3F.png',
  'himalayan airlines': 'https://images.kiwi.com/airlines/32/HC.png',
  'star1 airlines': 'https://images.kiwi.com/airlines/32/V9.png',
  'grozny avia': 'https://images.kiwi.com/airlines/32/ZG.png',
  'austral lineas aereas': 'https://images.kiwi.com/airlines/32/AU.png',
  'expressjet': 'https://images.kiwi.com/airlines/32/XE.png',
  'frontier flying service': 'https://images.kiwi.com/airlines/32/2F.png',
  'spring airlines': 'https://images.kiwi.com/airlines/32/9C.png',
  'kostromskie avialinii': 'https://images.kiwi.com/airlines/32/K1.png',
  'baltic air lines': 'https://images.kiwi.com/airlines/32/B1.png',
  'greenfly': 'https://images.kiwi.com/airlines/32/XX.png',
  'felix airways': 'https://images.kiwi.com/airlines/32/FU.png',
  'easyjet (ds)': 'https://images.kiwi.com/airlines/32/DS.png',
  'yamal airlines': 'https://images.kiwi.com/airlines/32/YL.png',
  'world airways': 'https://images.kiwi.com/airlines/32/WO.png',
  'wizz air hungary': 'https://images.kiwi.com/airlines/32/8Z.png',
  'jordan aviation': 'https://images.kiwi.com/airlines/32/R5.png',
  'air cote d\'ivoire': 'https://images.kiwi.com/airlines/32/HF.png',
  'tuifly nordic': 'https://images.kiwi.com/airlines/32/6B.png',
  'transwest air': 'https://images.kiwi.com/airlines/32/9T.png',
  'skywalk airlines': 'https://images.kiwi.com/airlines/32/AL.png',
  'swissair': 'https://images.kiwi.com/airlines/32/SR.png',
  'sata air acores': 'https://images.kiwi.com/airlines/32/SP.png',
  'ryan international airlines': 'https://images.kiwi.com/airlines/32/RD.png',
  'rossiya': 'https://images.kiwi.com/airlines/32/R4.png',
  'portugalia': 'https://images.kiwi.com/airlines/32/NI.png',
  'pb air': 'https://images.kiwi.com/airlines/32/9Q.png',
  'overland airways': 'https://images.kiwi.com/airlines/32/OJ.png',
  'origin pacific airways': 'https://images.kiwi.com/airlines/32/QO.png',
  'northwest airlines': 'https://images.kiwi.com/airlines/32/NW.png',
  'netjets': 'https://images.kiwi.com/airlines/32/1I.png',
  'maersk': 'https://images.kiwi.com/airlines/32/DM.png',
  'mng airlines': 'https://images.kiwi.com/airlines/32/MB.png',
  'viva air peru': 'https://images.kiwi.com/airlines/32/VV.png',
  'lufthansa cityline': 'https://images.kiwi.com/airlines/32/CL.png',
  'luftfahrtgesellschaft walter': 'https://images.kiwi.com/airlines/32/HE.png',
  'ltu austria': 'https://images.kiwi.com/airlines/32/L3.png',
  'air labrador': 'https://images.kiwi.com/airlines/32/WJ.png',
  'air arabia maroc': 'https://images.kiwi.com/airlines/32/3O.png',
  'abacus international': 'https://images.kiwi.com/airlines/32/1B.png',
  'bulgarian air charter': 'https://images.kiwi.com/airlines/32/H6.png',
  'klm cityhopper': 'https://images.kiwi.com/airlines/32/WA.png',
  'jetairfly': 'https://images.kiwi.com/airlines/32/JF.png',
  'jet airways': 'https://images.kiwi.com/airlines/32/9W.png',
  'horizon air': 'https://images.kiwi.com/airlines/32/QX.png',
  'régional': 'https://images.kiwi.com/airlines/32/YS.png',
  'kuzu airlines cargo': 'https://images.kiwi.com/airlines/32/GO.png',
  'globus': 'https://images.kiwi.com/airlines/32/GH.png',
  'aeroper': 'https://images.kiwi.com/airlines/32/PL.png',
  'atlas blue': 'https://images.kiwi.com/airlines/32/8A.png',
  'all nippon airways': 'https://images.kiwi.com/airlines/32/NH.png',
  'siam air': 'https://images.kiwi.com/airlines/32/O8.png',
  'air japan': 'https://images.kiwi.com/airlines/32/NQ.png',
  'corendon airlines europe': 'https://images.kiwi.com/airlines/32/XR.png',
  'tatarstan airlines': 'https://images.kiwi.com/airlines/32/U9.png',
  'air malawi': 'https://images.kiwi.com/airlines/32/QM.png',
  'air macau': 'https://images.kiwi.com/airlines/32/NX.png',
  'air north charter - canada': 'https://images.kiwi.com/airlines/32/4N.png',
  'aerocondor': 'https://images.kiwi.com/airlines/32/2B.png',
  'atlant-soyuz airlines': 'https://images.kiwi.com/airlines/32/3G.png',
  'carpatair': 'https://images.kiwi.com/airlines/32/V3.png',
  'atlas atlantique airlines': 'https://images.kiwi.com/airlines/32/L5.png',
  'caribbean airlines': 'https://images.kiwi.com/airlines/32/BW.png',
  'camair-co': 'https://images.kiwi.com/airlines/32/QC.png',
  'sichuan airlines': 'https://images.kiwi.com/airlines/32/3U.png',
  'wizz air ukraine': 'https://images.kiwi.com/airlines/32/WU.png',
  'buquebus líneas aéreas': 'https://images.kiwi.com/airlines/32/BQ.png',
  'virginwings': 'https://images.kiwi.com/airlines/32/YY.png',
  'homer air': 'https://images.kiwi.com/airlines/32/MR.png',
  'afriqiyah airways': 'https://images.kiwi.com/airlines/32/8U.png',
  'flynordic': 'https://images.kiwi.com/airlines/32/LF.png',
  'hawkair': 'https://images.kiwi.com/airlines/32/BH.png',
  'heli france': 'https://images.kiwi.com/airlines/32/8H.png',
  'helijet': 'https://images.kiwi.com/airlines/32/JB.png',
  'hellas jet': 'https://images.kiwi.com/airlines/32/T4.png',
  'hello': 'https://images.kiwi.com/airlines/32/HW.png',
  'masair': 'https://images.kiwi.com/airlines/32/M7.png',
  'miat mongolian airlines': 'https://images.kiwi.com/airlines/32/OM.png',
  'southjet cargo': 'https://images.kiwi.com/airlines/32/78.png',
  'united airways': 'https://images.kiwi.com/airlines/32/4H.png',
  'flexflight': 'https://images.kiwi.com/airlines/32/W2.png',
  'malév': 'https://images.kiwi.com/airlines/32/MA.png',
  'mandarin airlines': 'https://images.kiwi.com/airlines/32/AE.png',
  'grant aviation': 'https://images.kiwi.com/airlines/32/GV.png',
  'skagway air service': 'https://images.kiwi.com/airlines/32/N5.png',
  'sga airlines': 'https://images.kiwi.com/airlines/32/5E.png',
  'avianova (russia)': 'https://images.kiwi.com/airlines/32/AO.png',
  'aerolineas sosa': 'https://images.kiwi.com/airlines/32/P4.png',
  'panam world airways': 'https://images.kiwi.com/airlines/32/WQ.png',
  'ksy': 'https://images.kiwi.com/airlines/32/KY.png',
  'sochi air': 'https://images.kiwi.com/airlines/32/CQ.png',
  'senegal airlines': 'https://images.kiwi.com/airlines/32/DN.png',
  'businessair': 'https://images.kiwi.com/airlines/32/8B.png',
  'senic airlines': 'https://images.kiwi.com/airlines/32/YR.png',
  'mahan air': 'https://images.kiwi.com/airlines/32/W5.png',
  'go air': 'https://images.kiwi.com/airlines/32/G8.png',
  'aironix': 'https://images.kiwi.com/airlines/32/OG.png',
  'china northwest airlines (wh)': 'https://images.kiwi.com/airlines/32/WH.png',
  'jetsmart': 'https://images.kiwi.com/airlines/32/JA.png',
  'bqb lineas aereas': 'https://images.kiwi.com/airlines/32/5Q.png',
  'royal airways': 'https://images.kiwi.com/airlines/32/KG.png',
  'yangon airways ltd.': 'https://images.kiwi.com/airlines/32/YH.png',
  'ariana afghan airlines': 'https://images.kiwi.com/airlines/32/FG.png',
  'air costa': 'https://images.kiwi.com/airlines/32/LB.png',
  'latam argentina': 'https://images.kiwi.com/airlines/32/4M.png',
  'iberia express': 'https://images.kiwi.com/airlines/32/I2.png',
  'korongo airlines': 'https://images.kiwi.com/airlines/32/ZC.png',
  'sochi air chater': 'https://images.kiwi.com/airlines/32/Q3.png',
  'ansett australia': 'https://images.kiwi.com/airlines/32/AN.png',
  'askari aviation': 'https://images.kiwi.com/airlines/32/4K.png',
  'japan regio': 'https://images.kiwi.com/airlines/32/ZX.png',
  'luchsh airlines ': 'https://images.kiwi.com/airlines/32/L4.png',
  'papillon grand canyon helicopters': 'https://images.kiwi.com/airlines/32/HI.png',
  'salsa d\'haiti': 'https://images.kiwi.com/airlines/32/SO.png',
  'vasp': 'https://images.kiwi.com/airlines/32/VP.png',
  'fly-sax': 'https://images.kiwi.com/airlines/32/B5.png',
  'tradewind aviation': 'https://images.kiwi.com/airlines/32/TJ.png',
  'air namibia': 'https://images.kiwi.com/airlines/32/SW.png',
  'virgin australia airlines': 'https://images.kiwi.com/airlines/32/VA.png',
  'rotana jet': 'https://images.kiwi.com/airlines/32/RG.png',
  'tunisair': 'https://images.kiwi.com/airlines/32/TU.png',
  'brazil air': 'https://images.kiwi.com/airlines/32/GB.png',
  'europesky': 'https://images.kiwi.com/airlines/32/ES.png',
  'onechina': 'https://images.kiwi.com/airlines/32/1C.png',
  'chongqing airlines': 'https://images.kiwi.com/airlines/32/OQ.png',
  'branson air express': 'https://images.kiwi.com/airlines/32/1X.png',
  'ada air': 'https://images.kiwi.com/airlines/32/ZY.png',
  'commutair': 'https://images.kiwi.com/airlines/32/C5.png',
  'contact air': 'https://images.kiwi.com/airlines/32/C3.png',
  'continental micronesia': 'https://images.kiwi.com/airlines/32/CS.png',
  'darwin airline': 'https://images.kiwi.com/airlines/32/0D.png',
  'aeroflot russian airlines': 'https://images.kiwi.com/airlines/32/SU.png',
  'eastland air': 'https://images.kiwi.com/airlines/32/DK.png',
  'edelweiss air': 'https://images.kiwi.com/airlines/32/WK.png',
  'eurofly service': 'https://images.kiwi.com/airlines/32/GJ.png',
  'evergreen international airlines': 'https://images.kiwi.com/airlines/32/EZ.png',
  'air norway': 'https://images.kiwi.com/airlines/32/M3.png',
  'florida west international airways': 'https://images.kiwi.com/airlines/32/RF.png',
  'freebird airlines': 'https://images.kiwi.com/airlines/32/FH.png',
  'canxpress': 'https://images.kiwi.com/airlines/32/C1.png',
  'click (mexicana)': 'https://images.kiwi.com/airlines/32/QA.png',
  'world experience airline': 'https://images.kiwi.com/airlines/32/W1.png',
  'locair': 'https://images.kiwi.com/airlines/32/ZQ.png',
  'airblue': 'https://images.kiwi.com/airlines/32/ED.png',
  'n1': 'https://images.kiwi.com/airlines/32/N1.png',
  'jubba airways': 'https://images.kiwi.com/airlines/32/3J.png',
  'himalaya airlines': 'https://images.kiwi.com/airlines/32/H9.png',
  'empire airlines': 'https://images.kiwi.com/airlines/32/EM.png',
  'marusya airways': 'https://images.kiwi.com/airlines/32/Y8.png',
  'red jet mexico': 'https://images.kiwi.com/airlines/32/4X.png',
  'red jet canada': 'https://images.kiwi.com/airlines/32/QY.png',
  'usa sky cargo': 'https://images.kiwi.com/airlines/32/E1.png',
  'gnb linhas aereas': 'https://images.kiwi.com/airlines/32/GN.png',
  'next brasil': 'https://images.kiwi.com/airlines/32/XB.png',
  'air cargo germany': 'https://images.kiwi.com/airlines/32/6U.png',
  'norte lineas aereas': 'https://images.kiwi.com/airlines/32/N0.png',
  'indya airline group': 'https://images.kiwi.com/airlines/32/G1.png',
  'trans pas air': 'https://images.kiwi.com/airlines/32/T6.png',
  'cb airways uk ( interliging flights )': 'https://images.kiwi.com/airlines/32/1F.png',
  'fly brasil': 'https://images.kiwi.com/airlines/32/F1.png',
  'ccml airlines': 'https://images.kiwi.com/airlines/32/CB.png',
  'euro jet': 'https://images.kiwi.com/airlines/32/24.png',
  'aero vip (2d)': 'https://images.kiwi.com/airlines/32/2D.png',
  'yellowstone club private shuttle': 'https://images.kiwi.com/airlines/32/Y1.png',
  'harbour air (priv)': 'https://images.kiwi.com/airlines/32/H3.png',
  'transbrasil airlines': 'https://images.kiwi.com/airlines/32/TH.png',
  'twin jet': 'https://images.kiwi.com/airlines/32/T7.png',
  'air alps aviation (a6)': 'https://images.kiwi.com/airlines/32/A6.png',
  'black stallion airways': 'https://images.kiwi.com/airlines/32/BZ.png',
  'mandala airlines': 'https://images.kiwi.com/airlines/32/RI.png',
  'thomas cook belgium': 'https://images.kiwi.com/airlines/32/HQ.png',
  'china united': 'https://images.kiwi.com/airlines/32/KN.png',
  'boutiqueair': 'https://images.kiwi.com/airlines/32/4B.png',
  'fakeairline': 'https://images.kiwi.com/airlines/32/__.png',
  'arkia': 'https://images.kiwi.com/airlines/32/IZ.png',
  'cathay dragon': 'https://images.kiwi.com/airlines/32/KA.png',
  'citilink': 'https://images.kiwi.com/airlines/32/QG.png',
  'compagnie africaine d\'aviation': 'https://images.kiwi.com/airlines/32/E9.png',
  'air seoul': 'https://images.kiwi.com/airlines/32/RS.png',
  'cebgo': 'https://images.kiwi.com/airlines/32/DG.png',
  'volaris costa rica': 'https://images.kiwi.com/airlines/32/Q6.png',
  'wings air': 'https://images.kiwi.com/airlines/32/IW.png',
  'air do': 'https://images.kiwi.com/airlines/32/HD.png',
  'china airlines': 'https://images.kiwi.com/airlines/32/CI.png',
  'vivaaerobus': 'https://images.kiwi.com/airlines/32/VB.png',
  'fly540': 'https://images.kiwi.com/airlines/32/5H.png',
  'flair airlines': 'https://images.kiwi.com/airlines/32/F8.png',
  'cambodia angkor air': 'https://images.kiwi.com/airlines/32/K6.png',
  'dana air': 'https://images.kiwi.com/airlines/32/DA.png',
  'mango': 'https://images.kiwi.com/airlines/32/JE.png',
  'yeti airways': 'https://images.kiwi.com/airlines/32/YT.png',
  'boliviana de aviación': 'https://images.kiwi.com/airlines/32/OB.png',
  'thai airways international': 'https://images.kiwi.com/airlines/32/TG.png',
  'kan air': 'https://images.kiwi.com/airlines/32/K8.png',
  'tarom': 'https://images.kiwi.com/airlines/32/RO.png',
  'wow air': 'https://images.kiwi.com/airlines/32/WW.png',
  'southjet connect': 'https://images.kiwi.com/airlines/32/77.png',
  'southern airways express': 'https://images.kiwi.com/airlines/32/9X.png',
  'cm airlines': 'https://images.kiwi.com/airlines/32/CC.png',
  'comair': 'https://images.kiwi.com/airlines/32/OH.png',
  'colgan air': 'https://images.kiwi.com/airlines/32/9L.png',
  'ba cityflyer': 'https://images.kiwi.com/airlines/32/CJ.png',
  'orbit airlines azerbaijan': 'https://images.kiwi.com/airlines/32/O1.png',
  'hi fly (5k)': 'https://images.kiwi.com/airlines/32/5K.png',
  'nordic global airlines': 'https://images.kiwi.com/airlines/32/NJ.png',
  'regionaljet': 'https://images.kiwi.com/airlines/32/EE.png',
  'laser air': 'https://images.kiwi.com/airlines/32/QL.png',
  'air afrique': 'https://images.kiwi.com/airlines/32/RK.png',
  'southjet': 'https://images.kiwi.com/airlines/32/76.png',
  'austrian airlines': 'https://images.kiwi.com/airlines/32/OS.png',
  'ryanair': 'https://images.kiwi.com/airlines/32/FR.png',
  'south african airways': 'https://images.kiwi.com/airlines/32/SA.png',
  'aurigny air services': 'https://images.kiwi.com/airlines/32/GR.png',
  'air europa': 'https://images.kiwi.com/airlines/32/UX.png',
  'vietnam airlines': 'https://images.kiwi.com/airlines/32/VN.png',
  'southwest airlines': 'https://images.kiwi.com/airlines/32/WN.png',
  'turkish airlines': 'https://images.kiwi.com/airlines/32/TK.png',
  'cape air': 'https://images.kiwi.com/airlines/32/9K.png',
  'air malta': 'https://images.kiwi.com/airlines/32/KM.png',
  'american airlines': 'https://images.kiwi.com/airlines/32/AA.png',
  'yan air': 'https://images.kiwi.com/airlines/32/YE.png',
  'bek air': 'https://images.kiwi.com/airlines/32/Z9.png',
  'corendon': 'https://images.kiwi.com/airlines/32/XC.png',
  'pascan aviation': 'https://images.kiwi.com/airlines/32/P6.png',
  'euroatlantic airways': 'https://images.kiwi.com/airlines/32/YU.png',
  'central mountain air': 'https://images.kiwi.com/airlines/32/9M.png',
  'krasavia': 'https://images.kiwi.com/airlines/32/KI.png',
  'pawa dominicana': 'https://images.kiwi.com/airlines/32/7N.png',
  'air mandalay': 'https://images.kiwi.com/airlines/32/6T.png',
  'air cairo': 'https://images.kiwi.com/airlines/32/SM.png',
  'latam ecuador': 'https://images.kiwi.com/airlines/32/XL.png',
  'wingo airlines': 'https://images.kiwi.com/airlines/32/P5.png',
  'sncf': 'https://images.kiwi.com/airlines/32/2C.png',
  'aegean': 'https://images.kiwi.com/airlines/32/A3.png',
  'spirit airlines': 'https://images.kiwi.com/airlines/32/NK.png',
  'air burkina': 'https://images.kiwi.com/airlines/32/2J.png',
  'air botswana': 'https://images.kiwi.com/airlines/32/BP.png',
  'atran cargo airlines': 'https://images.kiwi.com/airlines/32/V8.png',
  'primera air nordic': 'https://images.kiwi.com/airlines/32/6F.png',
  'air marshall islands': 'https://images.kiwi.com/airlines/32/CW.png',
  'meridiana': 'https://images.kiwi.com/airlines/32/IG.png',
  'mokulele flight service': 'https://images.kiwi.com/airlines/32/MW.png',
  'delta air lines': 'https://images.kiwi.com/airlines/32/DL.png',
  'caspian airlines': 'https://images.kiwi.com/airlines/32/RV.png',
  'centralwings': 'https://images.kiwi.com/airlines/32/C0.png',
  'thai vietjet': 'https://images.kiwi.com/airlines/32/VZ.png',
  'island airlines': 'https://images.kiwi.com/airlines/32/IS.png',
  'islas airways': 'https://images.kiwi.com/airlines/32/IF.png',
  'racsa': 'https://images.kiwi.com/airlines/32/R6.png',
  'republic airlines': 'https://images.kiwi.com/airlines/32/RW.png',
  'canxplorer': 'https://images.kiwi.com/airlines/32/C2.png',
  'thai air cargo': 'https://images.kiwi.com/airlines/32/T2.png',
  '40-mile air': 'https://images.kiwi.com/airlines/32/Q5.png',
  'danube wings (v5)': 'https://images.kiwi.com/airlines/32/V5.png',
  'sharp airlines': 'https://images.kiwi.com/airlines/32/SH.png',
  'varig log': 'https://images.kiwi.com/airlines/32/LC.png',
  'vladivostok air': 'https://images.kiwi.com/airlines/32/XF.png',
  'wayraper': 'https://images.kiwi.com/airlines/32/7W.png',
  'etihad regional': 'https://images.kiwi.com/airlines/32/F7.png',
  'air sahara': 'https://images.kiwi.com/airlines/32/S2.png',
  'vision airlines': 'https://images.kiwi.com/airlines/32/V2.png',
  'astral aviation': 'https://images.kiwi.com/airlines/32/8V.png',
  'air tindi': 'https://images.kiwi.com/airlines/32/8T.png',
  'myanmar national airlines': 'https://images.kiwi.com/airlines/32/UB.png',
  'air creebec': 'https://images.kiwi.com/airlines/32/YN.png',
  'provincial airlines': 'https://images.kiwi.com/airlines/32/PB.png',
  'federai airlines': 'https://images.kiwi.com/airlines/32/7V.png',
  'vieques air link': 'https://images.kiwi.com/airlines/32/V4.png',
  'publiccharters.com': 'https://images.kiwi.com/airlines/32/P1.png',
  'vasco': 'https://images.kiwi.com/airlines/32/0V.png',
  'ewa air': 'https://images.kiwi.com/airlines/32/ZD.png',
  'allied air': 'https://images.kiwi.com/airlines/32/4W.png',
  'tajik air': 'https://images.kiwi.com/airlines/32/7J.png',
  'nomad aviation': 'https://images.kiwi.com/airlines/32/N6.png',
  'safarilink aviation': 'https://images.kiwi.com/airlines/32/F2.png',
  'sunwing': 'https://images.kiwi.com/airlines/32/WG.png',
  'aero vip': 'https://images.kiwi.com/airlines/32/WV.png',
  'one jet': 'https://images.kiwi.com/airlines/32/J1.png',
  'germania': 'https://images.kiwi.com/airlines/32/ST.png',
  'srilankan airlines': 'https://images.kiwi.com/airlines/32/UL.png',
  'air mediterranee': 'https://images.kiwi.com/airlines/32/ML.png',
  'lion air': 'https://images.kiwi.com/airlines/32/JT.png',
  'brit air': 'https://images.kiwi.com/airlines/32/DB.png',
  'yakutia airlines': 'https://images.kiwi.com/airlines/32/R3.png',
  'vietjet air': 'https://images.kiwi.com/airlines/32/VJ.png',
  'ruili airlines': 'https://images.kiwi.com/airlines/32/DR.png',
  'scat air': 'https://images.kiwi.com/airlines/32/DV.png',
  'fly safair': 'https://images.kiwi.com/airlines/32/FA.png',
  'west air china': 'https://images.kiwi.com/airlines/32/PN.png',
  'jambojet': 'https://images.kiwi.com/airlines/32/JX.png',
  'lucky air': 'https://images.kiwi.com/airlines/32/8L.png',
  'swiss international air lines': 'https://images.kiwi.com/airlines/32/LX.png',
  'krasavia (old iata)': 'https://images.kiwi.com/airlines/32/K9.png',
  'transportes aéreos guatemaltecos': 'https://images.kiwi.com/airlines/32/5U.png',
  'flynas': 'https://images.kiwi.com/airlines/32/XY.png',
  'greenland express': 'https://images.kiwi.com/airlines/32/J7.png',
  'spicejet': 'https://images.kiwi.com/airlines/32/SG.png',
  'westbahn': 'https://images.kiwi.com/airlines/32/5W.png',
  'jetstar asia airways': 'https://images.kiwi.com/airlines/32/3K.png',
  'dniproavia': 'https://images.kiwi.com/airlines/32/Z6.png',
  'ellinair': 'https://images.kiwi.com/airlines/32/EL.png',
  'mihin lanka': 'https://images.kiwi.com/airlines/32/MJ.png',
  'nature air': 'https://images.kiwi.com/airlines/32/5C.png',
  'tropic air limited': 'https://images.kiwi.com/airlines/32/9N.png',
  'hong kong airlines': 'https://images.kiwi.com/airlines/32/HX.png',
  'ravsa venezolana': 'https://images.kiwi.com/airlines/32/AW.png',
  'air arabia': 'https://images.kiwi.com/airlines/32/G9.png',
  'alas uruguay': 'https://images.kiwi.com/airlines/32/YZ.png',
  'cem air': 'https://images.kiwi.com/airlines/32/5Z.png',
  'eva air': 'https://images.kiwi.com/airlines/32/BR.png',
  'shaheen air international': 'https://images.kiwi.com/airlines/32/NL.png',
  'monarch': 'https://images.kiwi.com/airlines/32/ZB.png',
  'alrosa': 'https://images.kiwi.com/airlines/32/6R.png',
  'air berlin': 'https://images.kiwi.com/airlines/32/AB.png',
  'avior airlines': 'https://images.kiwi.com/airlines/32/9V.png',
  'asl airlines france': 'https://images.kiwi.com/airlines/32/5O.png',
  'wamos air': 'https://images.kiwi.com/airlines/32/EB.png',
  'air china': 'https://images.kiwi.com/airlines/32/CA.png',
  'westjet': 'https://images.kiwi.com/airlines/32/WS.png',
  'tui airlines netherlands': 'https://images.kiwi.com/airlines/32/OR.png',
  'flyvista': 'https://images.kiwi.com/airlines/32/GT.png',
  'insel air': 'https://images.kiwi.com/airlines/32/7I.png',
  'pobeda': 'https://images.kiwi.com/airlines/32/DP.png',
  'skymark airlines': 'https://images.kiwi.com/airlines/32/BC.png',
  'jetstar pacific': 'https://images.kiwi.com/airlines/32/BL.png',
  'nordavia': 'https://images.kiwi.com/airlines/32/5N.png',
  'valuair': 'https://images.kiwi.com/airlines/32/VF.png',
  'lc perú': 'https://images.kiwi.com/airlines/32/W4.png',
  'klm royal dutch airlines': 'https://images.kiwi.com/airlines/32/KL.png',
  'vanilla air': 'https://images.kiwi.com/airlines/32/JW.png',
  'angara airlines': 'https://images.kiwi.com/airlines/32/2G.png',
  'golden myanmar airlines': 'https://images.kiwi.com/airlines/32/Y5.png',
  'rusline': 'https://images.kiwi.com/airlines/32/7R.png',
  'jin air': 'https://images.kiwi.com/airlines/32/LJ.png',
  'sverigeflyg': 'https://images.kiwi.com/airlines/32/DC.png',
  'rwandair express': 'https://images.kiwi.com/airlines/32/WB.png',
  'sol líneas aéreas': 'https://images.kiwi.com/airlines/32/8R.png',
  'myanmar airways': 'https://images.kiwi.com/airlines/32/8M.png',
  'gol transportes aéreos': 'https://images.kiwi.com/airlines/32/G3.png',
  'bangkok airways': 'https://images.kiwi.com/airlines/32/PG.png',
  'orient thai airlines': 'https://images.kiwi.com/airlines/32/OX.png',
  'air new zealand': 'https://images.kiwi.com/airlines/32/NZ.png',
  'novoair': 'https://images.kiwi.com/airlines/32/VQ.png',
  'fake airline': 'https://images.kiwi.com/airlines/32/X9.png',
  'royal brunei airlines': 'https://images.kiwi.com/airlines/32/BI.png',
  'airbaltic': 'https://images.kiwi.com/airlines/32/BT.png',
  'flybe': 'https://images.kiwi.com/airlines/32/BE.png',
  'xpressair': 'https://images.kiwi.com/airlines/32/XN.png',
  'air kbz': 'https://images.kiwi.com/airlines/32/K7.png',
  'calm air': 'https://images.kiwi.com/airlines/32/MO.png',
  'blue islands': 'https://images.kiwi.com/airlines/32/SI.png',
  'peach aviation': 'https://images.kiwi.com/airlines/32/MM.png',
  'cinnamon air': 'https://images.kiwi.com/airlines/32/C7.png',
  'asian wings air': 'https://images.kiwi.com/airlines/32/YJ.png',
  'asiana airlines': 'https://images.kiwi.com/airlines/32/OZ.png',
  'malindo air': 'https://images.kiwi.com/airlines/32/OD.png',
  'cayman airways': 'https://images.kiwi.com/airlines/32/KX.png',
  'ravn alaska': 'https://images.kiwi.com/airlines/32/7H.png',
  'cobalt air': 'https://images.kiwi.com/airlines/32/CO.png',
  'regent airways': 'https://images.kiwi.com/airlines/32/RX.png',
  'air busan': 'https://images.kiwi.com/airlines/32/BX.png',
  'kenya airways': 'https://images.kiwi.com/airlines/32/KQ.png',
  'middle east airlines': 'https://images.kiwi.com/airlines/32/ME.png',
  'copa airlines': 'https://images.kiwi.com/airlines/32/CM.png',
  'air india express': 'https://images.kiwi.com/airlines/32/IX.png',
  'tui airways': 'https://images.kiwi.com/airlines/32/BY.png',
  'amaszonas': 'https://images.kiwi.com/airlines/32/Z8.png',
  'kuwait airways': 'https://images.kiwi.com/airlines/32/KU.png',
  'air antilles express': 'https://images.kiwi.com/airlines/32/3S.png',
  'saratov aviation division': 'https://images.kiwi.com/airlines/32/6W.png',
  'precision air': 'https://images.kiwi.com/airlines/32/PW.png',
  'tap portugal': 'https://images.kiwi.com/airlines/32/TP.png',
  'v air': 'https://images.kiwi.com/airlines/32/ZV.png',
  'yamal air': 'https://images.kiwi.com/airlines/32/YC.png',
  'japan airlines': 'https://images.kiwi.com/airlines/32/JL.png',
  'juneyao airlines': 'https://images.kiwi.com/airlines/32/HO.png',
  'brussels airlines': 'https://images.kiwi.com/airlines/32/SN.png',
  'primera air': 'https://images.kiwi.com/airlines/32/PF.png',
  'smartwings': 'https://images.kiwi.com/airlines/32/QS.png',
  'iberia airlines': 'https://images.kiwi.com/airlines/32/IB.png',
  'aws express': 'https://images.kiwi.com/airlines/32/B0.png',
  'braathens regional airlines': 'https://images.kiwi.com/airlines/32/TF.png',
  'bmi regional': 'https://images.kiwi.com/airlines/32/BM.png',
  'sas': 'https://images.kiwi.com/airlines/32/SK.png',
  '9 air': 'https://images.kiwi.com/airlines/32/AQ.png',
  'peruvian airlines': 'https://images.kiwi.com/airlines/32/P9.png',
  'nok air': 'https://images.kiwi.com/airlines/32/DD.png',
  'pakistan international airlines': 'https://images.kiwi.com/airlines/32/PK.png',
  'air tahiti nui': 'https://images.kiwi.com/airlines/32/TN.png',
  'adria airways': 'https://images.kiwi.com/airlines/32/JP.png',
  'satena': 'https://images.kiwi.com/airlines/32/9R.png',
  'aeromar': 'https://images.kiwi.com/airlines/32/VW.png',
  'garuda indonesia': 'https://images.kiwi.com/airlines/32/GA.png',
  'bearskin lake air service': 'https://images.kiwi.com/airlines/32/JV.png',
  'astra airlines': 'https://images.kiwi.com/airlines/32/A2.png',
  'air france': 'https://images.kiwi.com/airlines/32/AF.png',
  'mayair': 'https://images.kiwi.com/airlines/32/7M.png',
  'island air': 'https://images.kiwi.com/airlines/32/WP.png',
  'silver airways': 'https://images.kiwi.com/airlines/32/3M.png',
  'kalstar aviation': 'https://images.kiwi.com/airlines/32/KD.png',
  'city airline': 'https://images.kiwi.com/airlines/32/CF.png',
  'yunnan airlines': 'https://images.kiwi.com/airlines/32/3Q.png',
  'canadian airlines': 'https://images.kiwi.com/airlines/32/CP.png',
  'malaysia airlines': 'https://images.kiwi.com/airlines/32/MH.png',
  'aigle azur': 'https://images.kiwi.com/airlines/32/ZI.png',
  'scoot': 'https://images.kiwi.com/airlines/32/TR.png',
  'norwegian international': 'https://images.kiwi.com/airlines/32/D8.png',
  'blue wings': 'https://images.kiwi.com/airlines/32/QW.png',
  'bellview airlines': 'https://images.kiwi.com/airlines/32/B3.png',
  'airnorth': 'https://images.kiwi.com/airlines/32/TL.png',
  'jetblue airways': 'https://images.kiwi.com/airlines/32/B6.png',
  'transavia france': 'https://images.kiwi.com/airlines/32/TO.png',
  'nordwind airlines': 'https://images.kiwi.com/airlines/32/N4.png',
  'asky airlines': 'https://images.kiwi.com/airlines/32/KP.png',
  'air canada jazz': 'https://images.kiwi.com/airlines/32/QK.png',
  'skybahamas air': 'https://images.kiwi.com/airlines/32/Q7.png',
  'biman bangladesh airlines': 'https://images.kiwi.com/airlines/32/BG.png',
  'air india limited': 'https://images.kiwi.com/airlines/32/AI.png',
  'transavia': 'https://images.kiwi.com/airlines/32/HV.png',
  'nasair': 'https://images.kiwi.com/airlines/32/UE.png',
  'aeroméxico': 'https://images.kiwi.com/airlines/32/AM.png',
  'hong kong express airways': 'https://images.kiwi.com/airlines/32/UO.png',
  'chautauqua airlines': 'https://images.kiwi.com/airlines/32/RP.png',
  'philippines airasia': 'https://images.kiwi.com/airlines/32/PQ.png',
  'azul': 'https://images.kiwi.com/airlines/32/AD.png',
  'island spirit': 'https://images.kiwi.com/airlines/32/IP.png',
  'air vistara': 'https://images.kiwi.com/airlines/32/UK.png',
  'el al israel airlines': 'https://images.kiwi.com/airlines/32/LY.png',
  'airinuit': 'https://images.kiwi.com/airlines/32/3H.png',
  'orenburg airlines': 'https://images.kiwi.com/airlines/32/R2.png',
  'united': 'https://images.kiwi.com/airlines/32/UA.png',
  'intersky': 'https://images.kiwi.com/airlines/32/3L.png',
  'passaredo': 'https://images.kiwi.com/airlines/32/2Z.png',
  'utair': 'https://images.kiwi.com/airlines/32/UT.png',
  'tuifly': 'https://images.kiwi.com/airlines/32/X3.png',
  'bahamasair': 'https://images.kiwi.com/airlines/32/UP.png',
  'jazeera airways': 'https://images.kiwi.com/airlines/32/J9.png',
  'easyjet': 'https://images.kiwi.com/airlines/32/U2.png',
  'transaero airlines': 'https://images.kiwi.com/airlines/32/UN.png',
  'airasia india': 'https://images.kiwi.com/airlines/32/I5.png',
  'tway airlines': 'https://images.kiwi.com/airlines/32/TW.png',
  'firefly': 'https://images.kiwi.com/airlines/32/FY.png',
  'thai airasia x': 'https://images.kiwi.com/airlines/32/XJ.png',
  'indonesia airasia x': 'https://images.kiwi.com/airlines/32/XT.png',
  'alitalia': 'https://images.kiwi.com/airlines/32/AZ.png',
  'scoot - old': 'https://images.kiwi.com/airlines/32/TZ.png',
  'eurowings': 'https://images.kiwi.com/airlines/32/EW.png',
  'windward islands airways': 'https://images.kiwi.com/airlines/32/WM.png',
  'germanwings': 'https://images.kiwi.com/airlines/32/4U.png',
  'jetstar airways': 'https://images.kiwi.com/airlines/32/JQ.png',
  'thai lion air': 'https://images.kiwi.com/airlines/32/SL.png',
  'sky airline': 'https://images.kiwi.com/airlines/32/H2.png',
  'tuifly.be': 'https://images.kiwi.com/airlines/32/TB.png',
  'aerolineas argentinas': 'https://images.kiwi.com/airlines/32/AR.png',
  'condor': 'https://images.kiwi.com/airlines/32/DE.png',
  'tiger airways australia': 'https://images.kiwi.com/airlines/32/TT.png',
  'wizzair': 'https://images.kiwi.com/airlines/32/W6.png',
  'vivacolombia': 'https://images.kiwi.com/airlines/32/FC.png',
  'cebu pacific': 'https://images.kiwi.com/airlines/32/5J.png',
  'pegasus': 'https://images.kiwi.com/airlines/32/PC.png',
  'frontier airlines': 'https://images.kiwi.com/airlines/32/F9.png',
  'thai airasia': 'https://images.kiwi.com/airlines/32/FD.png',
  'indonesia airasia': 'https://images.kiwi.com/airlines/32/QZ.png',
  'airasia x': 'https://images.kiwi.com/airlines/32/D7.png',
  'vueling': 'https://images.kiwi.com/airlines/32/VY.png',
  'norwegian': 'https://images.kiwi.com/airlines/32/DY.png',
  'jet2': 'https://images.kiwi.com/airlines/32/LS.png',
  'blue panorama': 'https://images.kiwi.com/airlines/32/BV.png',
  'airasia': 'https://images.kiwi.com/airlines/32/AK.png',
  'interjet (abc aerolineas)': 'https://images.kiwi.com/airlines/32/4O.png',
  'aerolinea de antioquia': 'https://images.kiwi.com/airlines/32/1D.png',
  'flybondi': 'https://images.kiwi.com/airlines/32/FO.png',
}
